<?php
/**
* NO EDITAR * 
* ARCHIVO DE TRADUCCIONES *
**/
include_once('nuevogrutinetimport.php');
$importer = new nuevogrutinetimport();
$importer->l('Error al leer el archivo XML - ');
$importer->l('No se puede leer el archivo. Posiblemente ha sido borrado. Recargue la pagina para volver a descargarlo');
$importer->l('No se puede leer el archivo. Posiblemente ha sido borrado. Recargue la pagina para voler a descargarlo');
$importer->l('Se han procesado correctamente ');
$importer->l(' productos');
$importer->l('Se ha procesado el archivo de productos');
$importer->l('Se ha procesado correctamente el archivo de productos');
$importer->l('Se ha producido un error al procesar el archivo de Productos');
$importer->l(' fabricantes');
$importer->l('Se han procesado correctamente el archivo de fabricantes');
$importer->l('Se han procesado correctamente el archivo de Fabricantes');
$importer->l('Se han producido un error al procesar los fabricantes');
$importer->l('Se ha producido un error al procesar el archivo de Fabricantes');
$importer->l(' proveedores');
$importer->l('Se han procesado correctamente el archivo de proveedores');
$importer->l('Se han producido un error al procesar los proveedores');
$importer->l('Se ha producido un error al procesar el archivo de Proveedores');
$importer->l(' atributos');
$importer->l('Se han procesado correctamente el archivo de atributos');
$importer->l('Se ha producido un error al procesar el archivo de atributos');
$importer->l(' atributos por Producto');
$importer->l('Se han procesado correctamente el archivo de atributos por Producto');
$importer->l('Procesado correcto de los atributos por Producto');
$importer->l('Se han producido un error al procesar los atributos por Producto');
$importer->l('Se ha producido un error al procesar el archivo de atributos por Producto');
$importer->l(' bajas de producto');
$importer->l('Se han procesado correctamente el archivo de bajas de producto de Grutinet');
$importer->l('Procesado del archivo de bajas');
$importer->l('Se han producido un error al procesar las bajas');
$importer->l('Error al procesar el archivo de bajas');
$importer->l('Se ha producido un error al procesar el archivo de bajas de producto');
$importer->l(' sin stock');
$importer->l('Se han procesado correctamente el archivo de stocks');
$importer->l('Procesado del archivo de stocks');
$importer->l('Se han producido un error al procesar el archivo de stocks');
$importer->l('Error al procesar el archivo de stocks');
$importer->l('Se ha producido un error al procesar el archivo de stocks');
$importer->l('Este modulo no tiene una licencia valida');
$importer->l('Contacte con nosotros para obtener una licencia valida');
$importer->l('Producto compuesto por ');
$importer->l('unidades');
$importer->l('Se han procesado  los  productos de Grutinet');
$importer->l('Fin de proceso');
$importer->l('En proceso actualmente');
$importer->l('En espera actualmente');
$importer->l('Fichero Finalizado');
$importer->l('Atributos');
$importer->l('Bajas');
$importer->l('Stocks');
$importer->l('Productos');
$importer->l('Combinaciones');
$importer->l('Todos los archivos procesados');
$importer->l('Version Prestashop ');
$importer->l('Version: ');
$importer->l('Productos procesados:');
$importer->l('Atributos procesados: ');
$importer->l('Categorias procesadas: ');
$importer->l('Imagenes Pendientes: ');
$importer->l('Procesos Finalizados: ');
$importer->l('Estado general');
$importer->l('Nombre del Archivo');
$importer->l('Tipo');
$importer->l('Ultimo elemento procesado');
$importer->l('Lineas Procesadas');
$importer->l('Estado');
$importer->l('Importado desde');
$importer->l('Importado hasta');
$importer->l('Filtrar Fechas');
$importer->l('Id Producto');
$importer->l('Referencia');
$importer->l('Nombre');
$importer->l('Categoría');
$importer->l('Fecha');
$importer->l('Proceso correcto');
$importer->l('Se han procesado correctamente todos los hash ');
$importer->l(' hash');
$importer->l('Importacion y actualizacion del multicatalogo de GRUTINET');
$importer->l('Importa productos del multicatalogo de Grutinet');
$importer->l('La licencia no es valida. Es necesario configurar correctamente la licencia para usar este modulo');
$importer->l('Se ha producido un error al copiar el archivo de cron general a la carpeta de administracion');
$importer->l('Se ha producido un error al copiar el archivo de cron imagenes a la carpeta de administracion');
$importer->l('Se ha producido un error al copiar el archivo de estadisticas');
$importer->l('Error al instalar el tab');
$importer->l('Se ha producido un error al crear la direccion del proveedor');
$importer->l('Se ha producido un error al crear el proveedor');
$importer->l('Se ha producido un error al crear el cron');
$importer->l('Se ha producido un error al actualizar el cron');
$importer->l('Se ha producido un error al crear el directorio import');
$importer->l('Se ha producido un error al asignar permisos al directorio import');
$importer->l('Se ha producido un error al procesar las SQL');
$importer->l('Error al eliminar el tab');
$importer->l('Se ha producido un error al gestionar el sistema de actualizacion');
$importer->l('Configuracion de la descripcion corta no es correcta');
$importer->l('El tamaño de la descripcion corta es demasiado grande. Se ha puesto el maximo. Si quiere cambiarlo hagalo en preferencias->productos');
$importer->l('Configuracion de la descripcion corta no es correcta, es necesario marcar crear descripcion corta');
$importer->l('Sistema actualizacion correcto');
$importer->l('Gestion de impuestos actualizado correctamente');
$importer->l('Se ha producido un error al modificar la gestion de impuestos');
$importer->l('Token generado correctamente');
$importer->l('Cantidad actualizada correctamente');
$importer->l('Se ha producido un error al gestionar el sistema de SEO');
$importer->l('Actualizacion del SEO correcta');
$importer->l('Se ha producido un error al gestionar el sistema de SEO para nombres');
$importer->l('Actualizacion del SEO para nombres correcta');
$importer->l('Licencias guardadas correctamente');
$importer->l('Se ha producido un error en los siguientes plugins: ');
$importer->l('No hay ningun catalogo configurado.');
$importer->l('ATENCION: SU LICENCIA ESTA VACIA');
$importer->l('Debe introducir un numero de licencia valido para continuar');
$importer->l('ATENCION: SU LICENCIA NO ES VALIDA');
$importer->l('Si ejecuta el modulo sin licencia los resultados no seran validos');
$importer->l('Haga esto bajo su responsabilidad, Informax no dara soporte ni aceptar quejas o peticiones derivadas del uso sin licencia de nuestros productos');
$importer->l('El uso de nuestro software sin licencia constituye una infraccion de las leyes de propiedad intelectual, y sera puesta en conocimiento de las autoridades pertinentes');
$importer->l('Si cree que este mensaje es un error, por favor, pongase en contacto con nosotros, enviandonos codigo de licencia, nombre del modulo, dominio de la tienda y copia de la factura de pago');
$importer->l('Gestionar categorias');
$importer->l('Procesar manual');
$importer->l('Configuracion');
$importer->l('Configuracion Seo');
$importer->l('Ayuda');
$importer->l('Estadisticas');
$importer->l('Ultimos Productos');
$importer->l('Licencia');
$importer->l('Version modulo: ');
$importer->l('Configuracion SEO');
$importer->l('ATENCION: ');
$importer->l('Los campos a continuacion, seran cortados a la longitud adecuada antes de la inserccion. La longitud maxima sera la suma de la pre y post etiqueta junto al del texto original');
$importer->l('Pre-etiqueta MetaDescripcion');
$importer->l('Post-etiqueta MetaDescripcion');
$importer->l('Pre-etiqueta Metatitle');
$importer->l('Post-etiqueta Metatitle');
$importer->l('Pre-etiqueta Keywords');
$importer->l('Post-etiqueta Keywords');
$importer->l('Crear tags en productos');
$importer->l('Guardar');
$importer->l('Configuracion Nombre Producto');
$importer->l('Es necesario una licencia adicional para este plugin');
$importer->l('Puede obtenerla en: ');
$importer->l('Pre-etiqueta Nombre Producto');
$importer->l('Post-etiqueta Nombre Producto');
$importer->l('Insertar referencia al nombre del producto (Si se repite el nombre del producto)');
$importer->l('Posicion de la referencia');
$importer->l('Separador de la referencia');
$importer->l('Seleccionar Categoria padre y catalogos');
$importer->l('Refrescar lista');
$importer->l('Modo gestion margenes');
$importer->l('Seleccione el metodo de calculo de margenes, sobre el precio de compra, o sobre el precio de venta');
$importer->l('Sobre compra, se le aplica un porcentaje precio coste  * margen Beneficio');
$importer->l('Sobre venta, el margen es sobre el precio de Venta precio Formula = coste / ((100 - coste) / 100) ');
$importer->l('Sobre tarifa Oficial de Grutinet, tarifa oficial * margen Beneficio');
$importer->l('Tarifa Oficial de Grutinet');
$importer->l('Margen Global');
$importer->l('Importe Minimo de Beneficio');
$importer->l('Seleccionar porcentajes de categorias manualmente');
$importer->l('Se deben seleccionar margenes para todas las categorias o para ninguna.');
$importer->l('Debe configurar las tiendas en el tab configuracion antes de gestionar los margenes');
$importer->l('Invertir Seleccion');
$importer->l('Margen general');
$importer->l('Catalogo');
$importer->l('Tienda');
$importer->l('Proveedor');
$importer->l('Categoria padre');
$importer->l(' - Ninguna - ');
$importer->l(' - Todas - ');
$importer->l(' - Selecciona un proveedor - ');
$importer->l('Forzar procesado de archivo');
$importer->l('Catalogo:');
$importer->l('Ejecutar');
$importer->l('Token de acceso por cron');
$importer->l('ATENCION:');
$importer->l('Si cambia el token, tiene que cambiarlo tambien en las tareas de cron');
$importer->l('Debe enviarlo por get a las urls del servicio:');
$importer->l('Genera el token de configuracion');
$importer->l('Generar Token');
$importer->l('Token actual');
$importer->l('Elementos a procesar en cada llamada');
$importer->l('Numero de productos a importar');
$importer->l('Numero de atributos a importar');
$importer->l('Numero de imagenes a importar(No mas de 50)');
$importer->l('Gestion de tarifa');
$importer->l('Seleccione su tarifa');
$importer->l('Mapeado impuestos');
$importer->l('Marcando este check, las reglas de impuestos asignadas a los productos seran actualizadas en cada ejecucion del modulo.');
$importer->l('La actualizacion de las reglas tendran en cuenta la configuracion del mapeo de impuestos inferior si esta existe.');
$importer->l('Actualizar impuestos');
$importer->l('Puede mapear sus impuestos respecto a los enviados por grutinet en su archivo.');
$importer->l('Actualmente Grutinet envia los impuestos del 4, 10 y 21%.');
$importer->l('Si los impuestos de su pais o zona no corresponden con los ofrecidos por Grutinet, seleccione aqui las equivalencias');
$importer->l('Este mapeado de impuestos esta pensado especificamente para vendedores fuera de Espana, excluyendo las Islas Canarias');
$importer->l('Si no selecciona ningun impuesto local, o borra los valores de impuestos de Grutinet, los impuestos aplicados seran los enviados por Grutinet');
$importer->l('Impuesto Grutinet');
$importer->l('Impuesto Local');
$importer->l('Seleccione uno');
$importer->l('Opciones de actualizacion');
$importer->l('Activar Ajax');
$importer->l('Intervalo Refrescar las estadisticas');
$importer->l('Tiempo de Mensaje');
$importer->l('Actualizar Precios');
$importer->l('Actualizar Stock');
$importer->l('Desactivar productos');
$importer->l('Solo se aplicara a partir de la siguiente descarga de archivo');
$importer->l('Desactivar productos SIN STOCK');
$importer->l('Actualizar Imagenes');
$importer->l('Actualizar Descripciones');
$importer->l('Actualizar Seo');
$importer->l('Crear Imagenes de Categorias');
$importer->l('Crear Descripcion Corta');
$importer->l('Igual que la larga');
$importer->l('Cortada de la descripcion larga');
$importer->l('Caracteres');
$importer->l('Max: ');
$importer->l('Enviar Correos');
$importer->l('Indexar');
$importer->l('Este proceso es extremadamente lento');
$importer->l('Modo Debug');
$importer->l('Modo Debug para verificar si se esta realizando las tareas, Cuidado consume mucho almacenamiento en Base de Datos. Para verlo en Parametros Avanzados -> Protocolo de Sistema o Registro ');
$importer->l('Desactivar control Solapamiento');
$importer->l('Gestion Stocks');
$importer->l('Si un producto tiene menos de esta cantidad, sera desactivado');
$importer->l('Minimo stock para no desactivar el producto');
$importer->l('Licencia Principal');
$importer->l('La licencia es obligatoria para el correcto funcionamiento del modulo');
$importer->l('La licencia se deberia generar para el dominio: ');
$importer->l('Numero de Licencia');
$importer->l('Licencias Adicionales');
$importer->l('Introduzca las licencias para los plugins adicionales');
$importer->l('Puede obtener las licencias en: ');
$importer->l('Nombre Plugin');
$importer->l('Estado');
$importer->l('Archivo descargado correctamente');
$importer->l('Error al descargar el archivo');
$importer->l('Este producto tiene una licencia no valida. <br /> Si considera que es un error, contacte con nosotros');
$importer->l('Se ha finalizado el proceso, descargue nuevamente el archivo');
$importer->l('Verision nueva de modulo');
$importer->l('Importador del nuevo catalogo de Grutinet');
$importer->l('Informax - Tfno: 986484538');
$importer->l('No hay productos creados hoy');
?>
